### ISSUE TITLE
crach on calling api.getChatMember()

### ISSUE THREAD

**Issue by 1337G66k** [mast/telegram-bot-api#68]
/Users/g66k/Code/JavaScript/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^
StatusCodeError: 400 - {"ok":false,"error_code":400,"description":"Bad Request: wrong user_id specified"}
    at new StatusCodeError (/Users/g66k/Code/JavaScript/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/g66k/Code/JavaScript/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/g66k/Code/JavaScript/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/g66k/Code/JavaScript/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/Users/g66k/Code/JavaScript/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/Users/g66k/Code/JavaScript/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {

**Comment by mast** [comment]
Please check your user_id field. It have to be Integer identity of user. You get it in update at path `update.message.from.id`.
